# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/student_work_study_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=tejaswi0607
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=chikkatejaswi8@gmail.com
spring.mail.password=hbmvhatzlhmonmii
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Secret
jwt.secret=7d8cf226a4220b3ab42de8ea5e8346e9df1bc1e4d1f2e82b7acabcd05ed74b21
jwt.expiration=86400000

# Web
server.port=8080
